struct Novel {
    let ukTitle: String
    let ukPublicationYear: Int?
    let ukPublisher: String?
    let usPublicationYear: Int?
    let usTitle: String?
    let usPublisher: String?
    let series: String?
}

let novels: [Novel] = [
    Novel(ukTitle: "The Mysterious Affair at Styles", ukPublicationYear: 1921, ukPublisher: "The Bodley Head", usPublicationYear: 1920, usTitle: "The Mysterious Affair at Styles", usPublisher: "John Lane", series: "Hercule Poirot"),
    Novel(ukTitle: "The Secret Adversary", ukPublicationYear: 1922, ukPublisher: "The Bodley Head", usPublicationYear: 1922, usTitle: "The Secret Adversary", usPublisher: "Dodd, Mead & Co", series: "Tommy and Tuppence"),
    Novel(ukTitle: "The Murder on the Links", ukPublicationYear: 1923, ukPublisher: "The Bodley Head", usPublicationYear: 1923, usTitle: "The Murder on the Links", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "The Man in the Brown Suit", ukPublicationYear: 1924, ukPublisher: "The Bodley Head", usPublicationYear: 1924, usTitle: "The Man in the Brown Suit", usPublisher: "Dodd, Mead & Co", series: "Colonel Race"),
    Novel(ukTitle: "The Secret of Chimneys", ukPublicationYear: 1925, ukPublisher: "The Bodley Head", usPublicationYear: 1925, usTitle: "The Secret of Chimneys", usPublisher: "Dodd, Mead & Co", series: "Superintendent Battle"),
    Novel(ukTitle: "The Murder of Roger Ackroyd", ukPublicationYear: 1926, ukPublisher: "William Collins & Sons", usPublicationYear: 1926, usTitle: "The Murder of Roger Ackroyd", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "The Big Four", ukPublicationYear: 1927, ukPublisher: "William Collins & Sons", usPublicationYear: 1927, usTitle: "The Big Four", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "The Mystery of the Blue Train", ukPublicationYear: 1928, ukPublisher: "William Collins & Sons", usPublicationYear: 1928, usTitle: "The Mystery of the Blue Train", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "The Seven Dials Mystery", ukPublicationYear: 1929, ukPublisher: "William Collins & Sons", usPublicationYear: 1929, usTitle: "The Seven Dials Mystery", usPublisher: "Dodd, Mead & Co", series: "Superintendent Battle"),
    Novel(ukTitle: "The Murder at the Vicarage", ukPublicationYear: 1930, ukPublisher: "William Collins & Sons", usPublicationYear: 1930, usTitle: "The Murder at the Vicarage", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "Giant's Bread", ukPublicationYear: 1930, ukPublisher: "William Collins & Sons", usPublicationYear: 1930, usTitle: "Giant's Bread", usPublisher: "Doubleday", series: "Other"),
    Novel(ukTitle: "The Floating Admiral", ukPublicationYear: 1931, ukPublisher: "Hodder & Stoughton", usPublicationYear: 1932, usTitle: "The Floating Admiral", usPublisher: "Doubleday", series: "Mystery novel"),
    Novel(ukTitle: "The Sittaford Mystery", ukPublicationYear: 1931, ukPublisher: "William Collins & Sons", usPublicationYear: 1931, usTitle: "The Murder at Hazelmoor", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "Peril at End House", ukPublicationYear: 1932, ukPublisher: "William Collins & Sons", usPublicationYear: 1932, usTitle: "Peril at End House", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Lord Edgware Dies", ukPublicationYear: 1933, ukPublisher: "William Collins & Sons", usPublicationYear: 1933, usTitle: "Thirteen at Dinner", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Murder on the Orient Express", ukPublicationYear: 1934, ukPublisher: "William Collins & Sons", usPublicationYear: 1934, usTitle: "Murder in the Calais Coach", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Unfinished Portrait", ukPublicationYear: 1934, ukPublisher: "William Collins & Sons", usPublicationYear: 1934, usTitle: "Unfinished Portrait", usPublisher: "Doubleday", series: "Other"),
    Novel(ukTitle: "Why Didn't They Ask Evans?", ukPublicationYear: 1934, ukPublisher: "William Collins & Sons", usPublicationYear: 1935, usTitle: "The Boomerang Clue", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "Three Act Tragedy", ukPublicationYear: 1935, ukPublisher: "William Collins & Sons", usPublicationYear: 1934, usTitle: "Murder in Three Acts", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Death in the Clouds", ukPublicationYear: 1935, ukPublisher: "William Collins & Sons", usPublicationYear: 1935, usTitle: "Death in the Air", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "The A.B.C. Murders", ukPublicationYear: 1936, ukPublisher: "William Collins & Sons", usPublicationYear: 1936, usTitle: "The A.B.C. Murders", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Murder in Mesopotamia", ukPublicationYear: 1936, ukPublisher: "William Collins & Sons", usPublicationYear: 1936, usTitle: "Murder in Mesopotamia", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Cards on the Table", ukPublicationYear: 1936, ukPublisher: "William Collins & Sons", usPublicationYear: 1937, usTitle: "Cards on the Table", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Dumb Witness", ukPublicationYear: 1937, ukPublisher: "William Collins & Sons", usPublicationYear: 1937, usTitle: "Poirot Loses a Client", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Death on the Nile", ukPublicationYear: 1937, ukPublisher: "William Collins & Sons", usPublicationYear: 1938, usTitle: "Death on the Nile", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Appointment with Death", ukPublicationYear: 1938, ukPublisher: "William Collins & Sons", usPublicationYear: 1938, usTitle: "Appointment with Death", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Hercule Poirot's Christmas", ukPublicationYear: 1938, ukPublisher: "William Collins & Sons", usPublicationYear: 1939, usTitle: "Murder for Christmas", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Murder Is Easy", ukPublicationYear: 1939, ukPublisher: "William Collins & Sons", usPublicationYear: 1939, usTitle: "Easy to Kill", usPublisher: "Dodd, Mead & Co", series: "Superintendent Battle"),
    Novel(ukTitle: "And Then There Were None", ukPublicationYear: 1939, ukPublisher: "William Collins & Sons", usPublicationYear: 1941, usTitle: "And Then There Were None", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "Sad Cypress", ukPublicationYear: 1940, ukPublisher: "William Collins & Sons", usPublicationYear: 1940, usTitle: "Sad Cypress", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "One, Two, Buckle My Shoe", ukPublicationYear: 1940, ukPublisher: "William Collins & Sons", usPublicationYear: 1941, usTitle: "The Patriotic Murders", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Evil Under the Sun", ukPublicationYear: 1941, ukPublisher: "William Collins & Sons", usPublicationYear: 1941, usTitle: "Evil Under the Sun", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "N or M?", ukPublicationYear: 1941, ukPublisher: "William Collins & Sons", usPublicationYear: 1941, usTitle: "N or M?", usPublisher: "Dodd, Mead & Co", series: "Tommy and Tuppence"),
    Novel(ukTitle: "The Body in the Library", ukPublicationYear: 1942, ukPublisher: "William Collins & Sons", usPublicationYear: 1942, usTitle: "The Body in the Library", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "Five Little Pigs", ukPublicationYear: 1942, ukPublisher: "William Collins & Sons", usPublicationYear: 1942, usTitle: "Murder in Retrospect", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "The Moving Finger", ukPublicationYear: 1943, ukPublisher: "William Collins & Sons", usPublicationYear: 1942, usTitle: "The Moving Finger", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "Towards Zero", ukPublicationYear: 1944, ukPublisher: "William Collins & Sons", usPublicationYear: 1944, usTitle: "Towards Zero", usPublisher: "Dodd, Mead & Co", series: "Superintendent Battle"),
    Novel(ukTitle: "Death Comes as the End", ukPublicationYear: 1944, ukPublisher: "William Collins & Sons", usPublicationYear: 1945, usTitle: "Death Comes as the End", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "Sparkling Cyanide", ukPublicationYear: 1945, ukPublisher: "William Collins & Sons", usPublicationYear: 1945, usTitle: "Remembered Death", usPublisher: "Dodd, Mead & Co", series: "Colonel Race"),
    Novel(ukTitle: "The Hollow", ukPublicationYear: 1946, ukPublisher: "William Collins & Sons", usPublicationYear: 1946, usTitle: "Murder after Hours", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "The Labours of Hercules", ukPublicationYear: 1947, ukPublisher: "William Collins & Sons", usPublicationYear: 1947, usTitle: "The Labours of Hercules", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Taken at the Flood", ukPublicationYear: 1948, ukPublisher: "William Collins & Sons", usPublicationYear: 1948, usTitle: "There Is a Tide...", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Crooked House", ukPublicationYear: 1949, ukPublisher: "William Collins & Sons", usPublicationYear: 1949, usTitle: "Crooked House", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "A Murder Is Announced", ukPublicationYear: 1950, ukPublisher: "William Collins & Sons", usPublicationYear: 1950, usTitle: "A Murder Is Announced", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "They Came to Baghdad", ukPublicationYear: 1951, ukPublisher: "William Collins & Sons", usPublicationYear: 1951, usTitle: "They Came to Baghdad", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "Mrs McGinty's Dead", ukPublicationYear: 1952, ukPublisher: "William Collins & Sons", usPublicationYear: 1952, usTitle: "Mrs McGinty's Dead", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "They Do It with Mirrors", ukPublicationYear: 1952, ukPublisher: "William Collins & Sons", usPublicationYear: 1952, usTitle: "Murder with Mirrors", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "A Daughter's a Daughter", ukPublicationYear: 1952, ukPublisher: "William Heinemann Ltd", usPublicationYear: 1971, usTitle: "A Daughter's a Daughter", usPublisher: "Arbor House", series: "Other"),
    Novel(ukTitle: "After the Funeral", ukPublicationYear: 1953, ukPublisher: "William Collins & Sons", usPublicationYear: 1953, usTitle: "Funerals Are Fatal", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "A Pocket Full of Rye", ukPublicationYear: 1953, ukPublisher: "William Collins & Sons", usPublicationYear: 1953, usTitle: "A Pocket Full of Rye", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "Destination Unknown", ukPublicationYear: 1954, ukPublisher: "William Collins & Sons", usPublicationYear: 1954, usTitle: "So Many Steps to Death", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "Hickory Dickory Dock", ukPublicationYear: 1955, ukPublisher: "William Collins & Sons", usPublicationYear: 1955, usTitle: "Hickory Dickory Death", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Dead Man's Folly", ukPublicationYear: 1956, ukPublisher: "William Collins & Sons", usPublicationYear: 1956, usTitle: "Dead Man's Folly", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "4.50 from Paddington", ukPublicationYear: 1957, ukPublisher: "William Collins & Sons", usPublicationYear: 1957, usTitle: "What Mrs. McGillicuddy Saw!", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "Ordeal by Innocence", ukPublicationYear: 1958, ukPublisher: "William Collins & Sons", usPublicationYear: 1958, usTitle: "Ordeal by Innocence", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "Cat Among the Pigeons", ukPublicationYear: 1959, ukPublisher: "William Collins & Sons", usPublicationYear: 1959, usTitle: "Cat Among the Pigeons", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "The Adventure of the Christmas Pudding", ukPublicationYear: 1960, ukPublisher: "William Collins & Sons", usPublicationYear: 1960, usTitle: "The Adventure of the Christmas Pudding", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "The Pale Horse", ukPublicationYear: 1961, ukPublisher: "William Collins & Sons", usPublicationYear: 1961, usTitle: "The Pale Horse", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "The Mirror Crack'd from Side to Side", ukPublicationYear: 1962, ukPublisher: "William Collins & Sons", usPublicationYear: 1962, usTitle: "The Mirror Crack'd", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "The Clocks", ukPublicationYear: 1963, ukPublisher: "William Collins & Sons", usPublicationYear: 1963, usTitle: "The Clocks", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "A Caribbean Mystery", ukPublicationYear: 1964, ukPublisher: "William Collins & Sons", usPublicationYear: 1964, usTitle: "A Caribbean Mystery", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "At Bertram's Hotel", ukPublicationYear: 1965, ukPublisher: "William Collins & Sons", usPublicationYear: 1965, usTitle: "At Bertram's Hotel", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "Third Girl", ukPublicationYear: 1966, ukPublisher: "William Collins & Sons", usPublicationYear: 1966, usTitle: "Third Girl", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Endless Night", ukPublicationYear: 1967, ukPublisher: "William Collins & Sons", usPublicationYear: 1967, usTitle: "Endless Night", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "By the Pricking of My Thumbs", ukPublicationYear: 1968, ukPublisher: "William Collins & Sons", usPublicationYear: 1968, usTitle: "By the Pricking of My Thumbs", usPublisher: "Dodd, Mead & Co", series: "Tommy and Tuppence"),
    Novel(ukTitle: "Hallowe'en Party", ukPublicationYear: 1969, ukPublisher: "William Collins & Sons", usPublicationYear: 1969, usTitle: "Hallowe'en Party", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Passenger to Frankfurt", ukPublicationYear: 1970, ukPublisher: "William Collins & Sons", usPublicationYear: 1970, usTitle: "Passenger to Frankfurt", usPublisher: "Dodd, Mead & Co", series: "Mystery novel"),
    Novel(ukTitle: "Nemesis", ukPublicationYear: 1971, ukPublisher: "William Collins & Sons", usPublicationYear: 1971, usTitle: "Nemesis", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "Elephants Can Remember", ukPublicationYear: 1972, ukPublisher: "William Collins & Sons", usPublicationYear: 1972, usTitle: "Elephants Can Remember", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Postern of Fate", ukPublicationYear: 1973, ukPublisher: "William Collins & Sons", usPublicationYear: 1973, usTitle: "Postern of Fate", usPublisher: "Dodd, Mead & Co", series: "Tommy and Tuppence"),
    Novel(ukTitle: "Curtain", ukPublicationYear: 1975, ukPublisher: "William Collins & Sons", usPublicationYear: 1975, usTitle: "Curtain", usPublisher: "Dodd, Mead & Co", series: "Hercule Poirot"),
    Novel(ukTitle: "Sleeping Murder", ukPublicationYear: 1976, ukPublisher: "William Collins & Sons", usPublicationYear: 1976, usTitle: "Sleeping Murder", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "An Autobiography", ukPublicationYear: 1977, ukPublisher: "William Collins & Sons", usPublicationYear: 1977, usTitle: "An Autobiography", usPublisher: "Dodd, Mead & Co", series: "Non-fiction"),
    Novel(ukTitle: "Miss Marple's Final Cases and Two Other Stories", ukPublicationYear: 1979, ukPublisher: "William Collins & Sons", usPublicationYear: 1979, usTitle: "Miss Marple's Final Cases", usPublisher: "Dodd, Mead & Co", series: "Miss Marple"),
    Novel(ukTitle: "Problem at Pollensa Bay and Other Stories", ukPublicationYear: 1991, ukPublisher: "HarperCollins", usPublicationYear: 1992, usTitle: "The Harlequin Tea Set", usPublisher: "G.P. Putnam's Sons", series: "Hercule Poirot"),
    Novel(ukTitle: "While the Light Lasts and Other Stories", ukPublicationYear: 1997, ukPublisher: "HarperCollins", usPublicationYear: 1998, usTitle: "While the Light Lasts", usPublisher: "St. Martin's Press", series: "Mystery novel")
]
